/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mosampaio' at '17/06/16 13:43' with Gradle 2.13
 *
 * @author mosampaio, @date 17/06/16 13:43
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
